language: php

cache:
  directories:
    - vendor

matrix:
    include:
        - php: 5.6
          env:
            - COMPOSER_FLAGS='--prefer-lowest'
        - php: 7.0
        - php: 7.1
        - php: 7.2
        - php: 7.3
        - php: 7.4
          env:
            - PHPSTAN=1
        - php: 8.0
          env:
            - COVERAGE='--coverage --coverage-xml'
              XDEBUG_MODE=coverage
            - PHPSTAN=1

before_install:
    - if [[ ! $COVERAGE ]]; then phpenv config-rm xdebug.ini; fi;

before_script:
    - composer update -n $COMPOSER_FLAGS
    - if [[ $PHPSTAN ]]; then composer require --dev phpstan/phpstan ^0.12.99; fi;

script:
    - vendor/bin/codecept build
    - vendor/bin/phpcs
    - if [[ $PHPSTAN ]]; then vendor/bin/phpstan analyse -c phpstan.neon; fi;
    - vendor/bin/codecept run unit $COVERAGE

after_script:
    - if [[ $COVERAGE ]]; then ./coverage.sh; fi;
